version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: bioskuy
    ports:
      - "5432:5432"
    networks:
      - my_network

  app:
    build: .
    container_name: golang_app
    ports:
      - "3000:3000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: 12345678
      DB_HOST: db
      DB_NAME: bioskuy_test
      DB_PORT: 5432
      DRIVER_NAME: postgres
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

